version: '3.8'

services:
  raft_node_1:
    build: .
    container_name: raft_node_1
    command: ["1"]
    ports:
      - "5001:5000"

  raft_node_2:
    build: .
    container_name: raft_node_2
    command: ["2"]
    ports:
      - "5002:5000"

  raft_node_3:
    build: .
    container_name: raft_node_3
    command: ["3"]
    ports:
      - "5003:5000"
